# Generated by Django 6.0.6 on 2026-07-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
